### ISSUE TITLE
Unable to remove certain melting recipes w/ CrT

### ISSUE THREAD

**Issue by Matryoshika** [Shadows-of-Fire/Foundry#17]
Foundry: 3.1.1.0
Forge: 14.23.2.2615
CraftTweaker Script: https://pastebin.com/XpuTb2WD

What is expected to happen: Each ore is removed from Foundry's Melting recipe manager, and another recipe with different amount is re-added.

What happens: For some ores, removeRecipe errors and logs `Melting recipe not found.` Most other ores are unaffected. These ores retain their original recipe, and stays in JEI.

All affected ores do have an OreDict value (oreNether___ & oreEnd___)
Affected mods: Nether Metals, End Metals, OreCore
Issue happens with and without the IItemStacks being in arrays (and normal non-loop removeRecipes for these ores are also affected).
The removeRecipes at lines 5-13 are unaffected by this, and function properly.

**Comment by Shadows-of-Fire** [comment]
This nonsense happens because Foundry copies every TiC recipe it has to its own recipe managers.  This happens _after_ scripts are run on Foundry's end.  The Metals* set only has integration for TiC, so foundry was finding them and copying them after it ran the scripts.  [This build](https://www.dropbox.com/s/inygrw6y8lvpocq/Foundry-1.12.2-3.1.1.1.jar?dl=1) should work with that script, as I moved the CT integration to run last, but I'm busy and can't test it.

**Comment by Matryoshika** [comment]
Sadly, no discernable difference with the new build.
Same outcome as before.

**Comment by Shadows-of-Fire** [comment]
Alright.  I see what's wrong with it.  For whatever reason Nether/End metals registers their items under the wildcard meta (these blocks don't even have meta, jas why tho) and Foundry isn't accounting for that meta being in use here.  Had to dump the _entire_ melting registry to figure that out.  Fix soonish.
