### ISSUE TITLE
Crash with Botania's Exoflame and foundrys alloy furnace

### ISSUE THREAD

**Issue by scalda** [Shadows-of-Fire/Foundry#34]
Hi I am posting this here along with on botania's page. 

In Foolcraft 3 we have found a crash to desktop crash on placing an alloy furnace within range of a botania ExoFlame flower. Please find the Crash report [here](https://pastebin.com/ptvbWHDF)

Foundry: Foundry-1.12.2-3.2.0
Botania: Botania r1.10-354
Forge: 14.23.4.2739

https://github.com/scalda/Foolcraft_3/issues/179

**Comment by quat1024** [comment]
Likely caused by https://github.com/Shadows-of-Fire/Foundry/blob/5a9970dfd07863d64aed3dc58ce44ad170b92b1e/src/main/java/exter/foundry/tileentity/TileEntityAlloyFurnace.java#L101

Botania's mod ID is `botania` not `Botania`, causing this method to errantly get stripped

**Comment by Shadows-of-Fire** [comment]
Quality legacy codebase.   Bleh.

**Comment by quat1024** [comment]
just a quick find-and-replace `Botania` -> `botania` fixes the crash, but the mod integration doesn't seem to actually *work* haha

I'll investigate and open a pr

edit: The bug is TileEntityAlloyFurnace line 104, which has some messed up logic in it, it looks for only the first itemstack to be nonempty

**Comment by Shadows-of-Fire** [comment]
I can get it.  I'm gonna make that system a bit better overall anyway.

**Comment by quat1024** [comment]
Damn i was 2 slow
