### ISSUE TITLE
Foundry crashes if "CEU" is present

### ISSUE THREAD

**Issue by pyure** [Shadows-of-Fire/Foundry#39]
Hiya SHadows,

If the mod CEU (GT dependent) is present, Foundry crashes on load.

Any chance this is legitimately an issue on your side?  I would have posted on his side first except I can't find a repo to post on (ARR licensed mod).

https://pastebin.com/w5tF3uRn
Foundry-1.12.2-3.3.3.jar
Forge: 2739

**Comment by Shadows-of-Fire** [comment]
Is CEU modifying the melting point of liquid redstone?  That's the only way this crashes.

**Comment by Agrax** [comment]
In theory it shouldn’t be doing that, coz this is a mod that makes energy transformers. We’re trying to get in touch with CEU’s mod author to figure out the issue tho

**Comment by Tictim** [comment]
Hello, I am Tictim. Author of a tiny mod called [CEU](https://minecraft.curseforge.com/projects/ceu). I guess i could help you with some problems.

 At first I am genuinely confused because my mod has nothing to do with fluids. CEU adds just 80 machines...or 2 types of machines, and equivalent amounts of recipes. After searching for an hour guessing out what causes this situation I've managed to figure out how this happened.

 Ok quick explain. [Foundry's MeltingRecipe rejects fluid with melting point lower than 296.](https://github.com/Shadows-of-Fire/Foundry/blob/1.12.2/src/main/java/exter/foundry/recipes/MeltingRecipe.java) [And default temperature of all Gregtech's fluid is 295.](https://github.com/GregTechCE/GregTech/blob/c9a364efa2b4f3cee2e18ae78404d7bb30bf7dce/src/main/java/gregtech/api/unification/material/type/FluidMaterial.java) When CEU is not on (just Foundry + GT) Foundry and Thermal Foundation loads first. And it works just fine. But with CEU the Gregtech family loads first THEN Foundry(Thermal Foundation too). And it causes some problem.

 First, Gregtech creates their own Redstone fluid, and.. I dont know exactly what happens next. I guess Gregtech just takes its Redstone fluid..aaand it overrides Thermal Foundation's fluid. idk much about fluids. Anyway, then Foundry loads, takes Redstone fluid, adding some recipes...oops, wrong temperature.

 I guess Foundry's author needs to loose recipe's restriction, like set melting point at 300 to minimum, not throwing Exceptions? Its beyond my domain. Or he can just add _before:gregtech;_ at mod dependencies, which was what I did. I made a dummy mod called F**k, which loads between Foundry(after) and Gregtech(before).

 It was very interesting case. And swimming in Foundry's codes...and Thermal Foundation..and CoFH Damn Core..AND GTCE for making plausible story.. It was so much fun. _no its not_

[CEU-1.12.2-1.0.0.0-hot'''fix'''.zip](https://github.com/Shadows-of-Fire/Foundry/files/2385517/CEU-1.12.2-1.0.0.0-hot.fix.zip)
Change file extension to jar. There you have it.

 I hope it'll help.

**Comment by pyure** [comment]
Hiya Tictim.  I'm confused, you posted a really useful explanation and suggested that Foundry could loosen restrictions.  What does your CEU hotfix do?

**Comment by Tictim** [comment]
It adds dummy mod called F**k, in addition to CEU. It loads AFTER Foundry and BEFORE Gregtech, so it sorts mod loading order not to cause any problem.

**Comment by pyure** [comment]
Oh, I didn't connect those comments.  Thanks sir :)

**Comment by Shadows-of-Fire** [comment]
Until I can figure out the reason for that restriction, I've removed the crash and instead just made the min at that number.
